name: empty-project

on:
  push:
  pull_request:
    paths:
      - empty-project/**
      - .github/workflows/empty-project.yml

jobs:
  html5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        id: build
        uses: ./
        with:
          publish: html5
          blend: test/${{ github.workflow }}/${{ github.workflow }}.blend
          blender: latest/candidate
      - name: Result
        run: |
          echo "Code: ${{ steps.build.outputs.code }}"
          echo "Time: ${{ steps.build.outputs.time }}"
  krom-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        id: build
        uses: ./
        with:
          build: krom-linux
          blend: test/${{ github.workflow }}/${{ github.workflow }}.blend
          blender: latest/candidate
      - name: Result
        run: |
          echo "Code: ${{ steps.build.outputs.code }}"
          echo "Time: ${{ steps.build.outputs.time }}"
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: build
        uses: ./
        with:
          publish: linux-hl
          blender: latest/stable
          blend: test/${{ github.workflow }}/${{ github.workflow }}.blend
